import type { NextPage } from 'next';
import Head from 'next/head';
import { loginWithGoogle, logout, useUser } from '../lib/firebase';
import styles from '../styles/Home.module.css';

//import { gql, useQuery } from '@apollo/client';
import { useQuery } from 'urql';

const Home: NextPage = () => {

  const q = `query { queryTask { id title completed } }`;
  const { user } = useUser();

  // urql
  const [result] = useQuery({ query: q });

  // apollo
  //const result = useQuery(gql(q))

  console.log(result);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {user
          ? <><button onClick={logout}>Logout</button></>
          : <button onClick={loginWithGoogle}>Login with Google</button>}
      </main>
    </div>
  )
}

export default Home
